server:
  port: ${PORT:8761}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
management:
  port: 9091
  security:
    enabled: false
spring:
  application:
    name: demoeureka    