server:
  port: 8081
management:
  port: 9090
  security:
    enabled: false
eureka: 
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/ 
spring:
  application:
    name: api-gateway
security:    
    basic:
      enabled: false 
    user:
     password: none  
    oauth2:
      resource:
        filter-order: 3  
        jwt:
          key-value: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY----- 
        id: openid
        preferTokenInfo: true
zuul:
  routes:
    authenticationservice:
      path: /auth/**
      serviceId: AUTHENTICATIONSERVER      
      sensitive-headers: 
    demoresource:
      path: /peoples/**
      serviceId: PEOPLERESOURCE
      sensitive-headers: 
logging:
  level.org.springframework.security: DEBUG
      
        