server:
  port: 8081
management:
  port: 9090
  security:
    enabled: false
eureka: 
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/ 
spring:
  application:
    name: api-gateway
security:    
    basic:
      enabled: false 
    oauth2:
      resource:
        jwt:
          key-uri: http://AUTHENTICATIONSERVER/oauth/token_key 
zuul:
  routes:
    authenticationservice:
      path: /auth/**
      serviceId: AUTHENTICATIONSERVER      
      sensitive-headers: 
    demoresource:
      path: /peoples/**
      serviceId: DEMORESOURCE
      sensitive-headers: 
        