server:
  port: 8084
management:
  port: 9094
  security:
    enabled: false
eureka: 
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/  
spring:
  application:
    name: peopleresource  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:  
        dialect: org.hibernate.dialect.Oracle10gDialect
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:h2:mem:TEST
      driver-class-name: org.h2.Driver
      username: username
      password: sa
      hikari:
        idle-timeout: 10000             
security:    
    oauth2:
      resource:
        id: peopleresource
        jwt:
          key-value: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY-----    
    